services:

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    container_name: atm-recon-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    container_name: atm-recon-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:29092,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  spark-master:
    image: apache/spark:3.5.5
    container_name: atm-recon-spark-master
    entrypoint: ["/bin/sh", "-c", "/opt/spark/bin/spark-class org.apache.spark.deploy.master.Master"]
    ports:
      - "7077:7077"
      - "8080:8080"
    depends_on:
      - kafka
    volumes:
      - ./spark:/spark
      - ./producer:/producer
      - ./settlement:/settlement

  spark-worker:
    image: apache/spark:3.5.5
    container_name: atm-recon-spark-worker
    entrypoint: ["/bin/sh", "-c", "/opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://atm-recon-spark-master:7077"]
    depends_on:
      - spark-master
    volumes:
      - ./spark:/spark
      - ./producer:/producer
      - ./settlement:/settlement

  postgres:
    image: postgres:15
    container_name: atm-recon-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: atm_user
      POSTGRES_PASSWORD: atm_pass
      POSTGRES_DB: atm_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  airflow:
    image: apache/airflow:2.9.1
    container_name: atm-recon-airflow
    depends_on:
      - postgres
    ports:
      - "8082:8080"
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=postgresql+psycopg2://atm_user:atm_pass@postgres/atm_db
    volumes:
      - ./airflow/dags:/opt/airflow/dags
    command: >
      bash -c "airflow db init &&
               airflow webserver"

volumes:
  postgres_data: